models/FirstModel.php
<?php

namespace app\models;

use app\core\BaseModel;


class FirstModel extends BaseModel {
	
	public $test = 'test';

}

controllers/HomeController.php
<?php

namespace app\controllers;

use app\core\BaseController;
use app\core\ActiveRecord;
use app\core\Request;

class HomeController extends BaseController
{

	public function actionIndex(){
		
		$page_start = 0;
		$page = 1;
		$type = 'asc';
		$order_by = 'username';

		if(isset($_GET['page'])){
			$page = $_GET['page'];
			$page_start = $page * 3 - 3;

		}

		if(isset($_GET['type'])){
			$type = $_GET['type']=='asc' ? 'desc' : 'asc';
		}

		if(isset($_GET['order_by'])){
			$order_by = $_GET['order_by'];
		}

		$pagination_count = ceil(count(ActiveRecord::findBySql('select * from express_tasks'))/3);

		$tasks = ActiveRecord::findBySql('select * from express_tasks order by '.$order_by.' '.$type.' limit '.$page_start.',3');

		return $this->render("index", [
			'tasks' => $tasks,
			'pagination_count' => $pagination_count,
			'page' => $page,
			'type' => $type,
		]) ;

	}

	public function actionEnteringdata(){

		$errors = [];

		if(isset($_POST['submit_button'])){

			

			$username = $_POST['username'];
			$email = $_POST['email'];
			$task = $_POST['text_task'];
			$status = $_POST['status'];
			$image = $_FILES['image_file'];

			if(!$status){
				$status = 0;
			}

		
			foreach($_POST as $key => $value){

		    	if($key != 'status' && $key != 'submit_button' &&  empty($value)){
		    		$errors[] = $key.' field cannot be empty';
		    	}
		    }


			if(isset($image) && empty($image['error']) && count($errors) <=0){

				$uploaddir = 'uploads/';
     			$uploadfile = $uploaddir . basename($_FILES['image_file']['name']);

				if($this->imageUploading($_FILES) != 'true'){
					$errors[] = $this->imageUploading($_FILES);
				}

		    }


		    if(count($errors) <=0){

				ActiveRecord::save("INSERT INTO express_tasks (username, email, text, image, status)
				VALUES ('".$username."','".$email."','".$task."','".$uploadfile."','".$status."')");
				return $this->redirect('/home/index');
		    }

		}

		return $this->render("enter_data", [
			'errors' => $errors,
		]) ;

	}

	public function actionLogin(){

		if(isset($_POST['login'])){

			if(isset($_POST['username']) && isset($_POST['password'])){

				$username = $_POST['username'];
				$password = $_POST['password'];

				$data = ActiveRecord::login($username, $password);

				if(count($data) <= 0){

					$_SESSION['fail'] = 'Uncorrect name or password!'; 

				} else {

					$_SESSION['logged'] = 'Welcome '.$username;
      				$_SESSION['username'] = $username;
      				unset($_SESSION['fail']);
      				return $this->redirect('/home/index');
				}

			}

		}
		
		return $this->render("login") ;

	}

	public function actionLogout(){

		unset($_SESSION['logged']);
		unset($_SESSION['username']);

		return $this->redirect('/home/index') ;

	}


	public function imageUploading($image){

			$data = true;

			$image_types = ['jpeg', 'gif', 'png'];
			$file_type = explode('/', $_FILES['image_file']['type'])[1];

			if (!in_array($file_type, $image_types)){

				$data = 'Images type mustbe gif, jpg, or png';
				return $data;

			}


			$uploaddir = 'uploads/';

	      	if(!is_writable($uploaddir)){
	      		echo 'folder is not writable !'; die();
	      	} 

     		$uploadfile = $uploaddir . basename($_FILES['image_file']['name']);
      		$data = move_uploaded_file($_FILES['image_file']['tmp_name'], $uploadfile);

			$th_max_width = 320;
			$th_max_height = 240;
			

	    	list($width, $height, $type, $mime) = getimagesize($uploadfile);
	  		$ratio = ($width > $height) ? $th_max_width/$width : $th_max_height/$height; 
			$newwidth = round($width * $ratio); 
			$newheight = round($height * $ratio);

			$resized_image = imagecreatetruecolor($newwidth, $newheight);

			switch ($file_type){
				case 'gif': 
				  $source = imagecreatefromgif($uploadfile); 
				  break; 

				case 'jpeg': 
				  $source = imagecreatefromjpeg($uploadfile); 
				  break; 
				
				case 'png': 
				  $source = imagecreatefrompng($uploadfile); 
				  break;  
			}

			$data = imagecopyresampled($resized_image, $source, 0, 0, 0, 0, $newwidth, $newheight, $width, $height);

			if($data){
				$data = 'true';
			} else {
				$data = 'false';
			}

			return $data;
	}

	public function actionTaskstatus(){

		$data = false;

		if(isset($_GET['task_id']) && isset($_GET['status'])){

			$task_id = $_GET['task_id'];
			$status = $_GET['status'];
			$sql = 'UPDATE express_tasks SET status = '.$status.' where id = '.$task_id;
			ActiveRecord::update($sql);
			return $this->redirect('/home/index');
			$data = true;

		}

		return $data;

	}

}

views/home/enter_data.php
<h2>Creating a new task</h2>

<div class="col-md-7">
	

	<?php foreach($errors as $items):?>
		<?php echo $items.'<br />'?>
	<?php endforeach?>


</div>



<div class="col-md-7">
<form class="form-horizontal my_bee_jee_form" action="/home/enteringdata" method="POST" enctype="multipart/form-data">

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="username" placeholder="Email" name="username">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="email" placeholder="email" name="email">
    </div>
  </div>

   <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Text task</label>
    <div class="col-sm-10">
      <textarea type="text" class="form-control bee_jee_textarea" id="task" placeholder="task" rows="6" name="text_task"></textarea>
    </div>
  </div>

   <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Image</label>
    <div class="col-sm-10">
      <input type="file" class="form-control" id="task" placeholder="task" name="image_file">
    </div>
  </div>

    <?php $checked = '';?>
    <div class="form-group">
	    <label for="inputPassword3" class="col-sm-2 control-label">Task status</label>
	    <div class="col-sm-10">
	      <input type="checkbox" class="status" id="status" value=1 name="status" <?=$checked?> >
	    </div>
	</div>
  <div class="form-group">

    <div class="col-sm-offset-2 col-sm-10">
      	<button type="submit" class="btn btn-default" name="submit_button">Enter</button>
      	<span class="btn btn-default preview_button" name="">Preview</span>
    </div>

  </div>

</form>
</div>


<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Task List</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="bee_jee_preview_modal"></div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

views/home/index.php
  <h2>Task list</h2>

  <?php $disabled = 'disabled';?>
  <?php if(isset($_SESSION['logged'])){$disabled = '';}?>

         
  <table class="table">
    <thead>
      <tr>
        <th>user id</th>
        <th><a href = "/home/index?order_by = username&type=<?=$type?>&page=<?=$page?>">Username</a></th>
        <th><a href = "/home/index?order_by = email&type=<?=$type?>&page=<?=$page?>">Email</a></th>
        <th>Text</th>
        <th>Image</th>
        <th><a href = "/home/index?order_by = status&type=<?=$type?>&page=<?=$page?>">Status</a></th>
        <th>Check</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($tasks as $items):?>
      <tr>
        <td><?=$items['id']?></td>
        <td><?=$items['username']?></td>
        <td><?=$items['email']?></td>
        <td><?=$items['text']?></td>
        <td><img src="/<?=$items['image']?>" width="100"></td>
        <td><?php if($items['status'] == 1){echo 'Done'; $status = "checked";} else {echo 'Undone'; $status="";}?></td>
        <td> <input type="checkbox" class="bee_jee_task_status" id="status" value=1 name="status" model_id = "<?=$items['id']?>" data-status="<?=$items['status']?>" <?=$disabled?> <?=$status?>></td>
      </tr>
  	<?php endforeach;?>
    </tbody>
  </table>
</div>

<div style="display: flex; justify-content: center;">
<nav aria-label="Page navigation">
  <ul class="pagination">

    <?php $active = '';?>
    <?php $prev = $page-1; if(($page-1) <= 1){$prev = 1;}?>

    <li>
      <a href="/home/index?page=<?=$prev?>" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>

    <?php for($i = 1; $i <= $pagination_count; $i++):?>
    	<li class="<?php if($i==$page){echo 'active';}?>"><a href="/home/index?page=<?=$i?>"><?=$i?></a></li>
    <?php endfor;?>

    <?php $next = $page+1; if(($page+1) >= $i){$next = $i-1;}?>

    <li>
      <a href="/home/index?page=<?=$next?>" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>

  </ul>
</nav>
</div>

views/home/login.php
<div style="display: flex;flex-direction: column; align-items: center;">
<h2 style="padding-bottom: 15px">Admin login page</h2>
  


<div class="col-md-7">

  <?php if(isset($_SESSION['fail'])):?>
    <h4>
      <?='Uncorrect username or password'?>
    </h4>
<?php endif;?>

<form class="form-horizontal" action="" method="POST" enctype="multipart/form-data">

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Username</label>
    <div class="col-sm-10">
      <input type="text" class="form-control" id="username" placeholder="Email" name="username" autocomplete="off">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-10">
      <input type="password" class="form-control" id="email" placeholder="email" name="password" autocomplete="off">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default" name="login">Login</button>
    </div>
  </div>
</form>
</div>
</div>
<script type="text/javascript">
  

</script>

views/layouts/main.php
<?php

use app\core\Action;


	$status = '';
	$user = '';
	if(isset($_SESSION['logged'])){
      	$status = 'logged';
      	$user = $_SESSION['username'];
    } else {
     	$status = 'guest';
    }

    $action = Action::$action_name;

?>


<?php require "../config/main_config.php";?>





<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name = "viewport" content ="width=device-width, initial-scale=1">
	<title>express_task</title>
	<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
</head>
<body>
	<br>
	<div class="container">
		<ul class="nav nav-pills nav-justified">
			<li class='<?php if($action=='index'){echo 'active';}?>'><a href="<?=$main_config['base']['url'].'/home/index'?>">Home</a></li>
			<li class='<?php if($action=='enteringdata'){echo 'active';}?>'><a href="<?=$main_config['base']['url'].'/home/enteringdata'?>">Entering Data</a></li>

			<?php if($status=='guest'):?>
				<li class='<?php if($action=='login'){echo 'active';}?>'><a href="<?=$main_config['base']['url'].'/home/login'?>">Login</a></li>
			<?php endif;?>

			<?php if($status=='logged'):?>
				<li><a href="<?=$main_config['base']['url'].'/home/logout'?>">Logout(<?=$user?>)</a></li>
			<?php endif;?>

		</ul>

	<?php echo $content;?>

	</div>
	<script type="text/javascript" src="/js/jQuery.js"></script>
	<script type="text/javascript" src="/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="/js/my_jquery.js"></script>

</body>


</html>